version: '3.8'

services:
  frontend-react:
    image: satya490/multi-lang-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend-python
      - backend-java
      - backend-go
    networks:
      - app-network

  backend-python:
    image: satya490/multi-lang-python:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    networks:
      - app-network

  backend-java:
    image: satya490/multi-lang-java:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend-go:
    image: satya490/multi-lang-go:latest
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
