name: Build and Push Docker Images

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: satya490
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push React Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend-react
        push: true
        tags: satya490/multi-lang-frontend:latest
        platforms: linux/amd64,linux/arm64

    - name: Build and push Python Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend-python
        push: true
        tags: satya490/multi-lang-python:latest
        platforms: linux/amd64,linux/arm64

    - name: Build and push Java Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend-java
        push: true
        tags: satya490/multi-lang-java:latest
        platforms: linux/amd64,linux/arm64

    - name: Build and push Go Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend-go
        push: true
        tags: satya490/multi-lang-go:latest
        platforms: linux/amd64,linux/arm64
